config/routes.rb
Rails.application.routes.draw do
  get 'tasks/new'
  get 'projects/new'
  get 'login/new'
  root 'static_pages#home'
  get 'users/new'
  get 'login', to: 'login#new'
  post 'login', to: 'login#create'
  get 'logout', to: 'login#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users
  resources :projects
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    belongs_to :user
    has_many :tasks, dependent: :destroy

end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :project
end

app/models/user.rb
class User < ApplicationRecord
    has_many :projects, dependent: :destroy
    validates :email, uniqueness: true, presence: true
    validates :password, confirmation: true, length: {minimum: 6}, presence: true
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
include LoginHelper
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def new

  end

  def create
    user = User.find_by(email: params[:login][:email].downcase)
    if user && user.authenticate(params[:login][:password])
      log_in(user)
      redirect_to root_path
    else
      flash[:danger] = 'Invalid email or password'
      redirect_to root_path
    end
  end

  def destroy
    logout
    redirect_to root_url
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :check_user, only: [:create, :new, :index, :destroy, :edit, :update]

  def index
    @projects = current_user.projects.all
    render 'index'
  end

  def new
    @project = Project.new
  end

  def create
    @project = current_user.projects.build(project_params)
    if @project.save
      flash[:success] = "Project created successfully"
      redirect_to projects_path
    else
      flash[:danger] = "Title is invalid"
      redirect_to new_project_path
    end
  end

  def edit
    @project = current_user.projects.find(params[:id])
  end

  def update
    @project = current_user.projects.find(params[:id])
    if @project.update(project_params)
      flash[:success] = "Your Project is updated"
      redirect_to projects_path
    else

      flash[:success] = "Project is not updated"
      render 'edit'
    end
  end


  def destroy
    project = current_user.projects.find(params[:id])
    project.destroy
    flash[:success] = "Project deleted successfully"
    redirect_to projects_path
  end

  private
  def project_params
    params.require(:project).permit(:pname)
  end

  def check_user
    redirect_to root_path unless current_user
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :check_user, only: [:create, :new, :index, :destroy, :edit, :update]

  def current_project
    @project = current_user.projects.find((params[:pid]))
    
  end

  def index
    @project = current_project
    @tasks = @project.tasks
  end

  def new
    @pid = params[:pid]
    @task = Task.new
  end

  def edit
    @project = current_project
    @task = @project.tasks.find(params[:id])
  end

  def update
    @project = current_project
    @task = @project.tasks.find(params[:id])
    @task.update(task_params)
    flash[:success] = "Task Updated"
    redirect_to tasks_path(pid: @project.id)
  end

  def create
    @project = current_project
    @task = @project.tasks.new(task_params)
    if @task.save
      flash[:success] = "task created successfully"
      redirect_to tasks_path(pid: @project.id)
    else
      flash[:danger] = "Title is invalid"
      redirect_to new_task_path
    end
  end

  def destroy
    @project = current_project
    @task = @project.tasks.find(params[:id])
    @task.destroy
    redirect_to tasks_path(pid: @project.id)
  end

 

  private
  def task_params
    params.require(:task).permit(:tname)
  end

  def check_user
    redirect_to root_path unless current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'Your Account Created Successfully'
      redirect_to login_path
    else
      flash[:danger] = 'Please enter valid user or password'
      redirect_to new_user_path
    end
  end

  private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
    def log_in(user)
        session[:user_id] = user.id
    end

    def current_user
        if session[:user_id]
            @current_user ||= User.find_by(id: session[:user_id])
            return @current_user
        end
    end

    def logged_in?
        !current_user.nil?
    end

    def logout
        session.delete(:user_id)
        @current_user=nil
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
    <header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    
    <%= link_to "Task Managment", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
         
          <li><%= link_to "Home", root_path, class: "nav-link active" %></li>
        </li>
               
        <li class="nav-item">
        <% if logged_in? %>
        <li><%= link_to "Projects",  projects_path, class: "nav-link active" %></li>
        <li><%= link_to "Logout",  logout_path, data: {turbo_method: :delete}, class: "nav-link active" %></li>
        <% else %>
        <li><%= link_to "SignUp", new_user_path, class: "nav-link active" %></li>
        <li><%= link_to "Login",  login_path, class: "nav-link active" %></li>
        <% end %>

        </li>


      
      
      </ul>

    </div>
  </div>
</nav>
  </header>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <%= render partial: "layouts/header.html.erb" %>
  <% flash.each do |msg_type, msg| %>
  <%= msg %>
  <% end %>
  <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>


  </body>
</html>

app/views/login/new.html.erb
<% provide(:title, "Login") %>

<div class="container border border-dark shadow w-50 rounded-2 p-2 mt-4 ">

<h1 class="text-center">Login</h1>
<div class="text-start w-50 mx-auto" >
<%= form_with(url: login_path, scope: :login, local: true) do |f| %>

<%= f.label :email, "Email" %>
<br>
<%= f.email_field :email %>
<br>
<br>

<%= f.label :password, "Password" %>
<br>
<%= f.password_field :password %>
<br>
<br>

<%= f.submit "Login", class: "btn btn-outline-success" %>
<br>
<%= link_to "new user?", new_user_path %>

<% end %>
</div>
</div>

app/views/projects/edit.html.erb
<% provide(:title, "Edit Project") %>

<div class="container border border-dark shadow w-50 rounded-2 p-2 mt-4 ">


<div class="text-start w-50 mx-auto" >
<%= form_with(model: @project, local: true) do |f| %>

<%= f.label :pname, "Title" %>
<br>
<%= f.text_field :pname %>
<br>
<br>


<%= f.submit "Update Project", class: "btn btn-outline-success" %>

<% end %>
</div>
</div>

app/views/projects/index.html.erb
<% provide(:title, "All Projects") %>

<div class="container mt-4">

<% if @projects %>
<h1 class="mb-4">List Of All Projects</h1>
<table class="table">
  <tbody>
      <tr>
      <th scope="col">No</th>
      <th scope="col">Projects</th>
    </tr>
  </thead>
  <% @count = 0 %>
    <% @projects.each do |project| %>
    <tr>
  
<th scope="row"> <% @count += 1 %> </th>
      <td><%= link_to project.pname, tasks_path(pid: project.id) %></td>
      <td><%= link_to "Update", edit_project_path(project) %></td>
      <td><%= link_to "Delete", project, method: :delete %></td>
      <td><%= link_to "Add New Task", new_task_path(pid: project.id) %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<% else %>
<h2>No tasks</h2>
<% end %>
<%= link_to "Create New Project", new_project_path %>

</div>

app/views/projects/new.html.erb
<div class="container border border-dark shadow w-50 rounded-2 p-2 mt-4 ">


<div class="text-start w-50 mx-auto" >
<%= form_with(model: @project, local: true) do |f| %>

<%= f.label :pname, "Title" %>
<br>
<%= f.text_field :pname %>
<br>
<br>


<%= f.submit "Create Project", class: "btn btn-outline-success" %>

<% end %>
</div>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, "Task Management") %>
<div class="container-fluid">
<h1>Welcome To Task Management</h1>
<p>Let's create the project</p>

<% if current_user %>
<%= link_to "Create Project", new_project_path %>
<% else %>
<%= link_to "Login", login_path %>
<% end %>
</div>

app/views/tasks/edit.html.erb
<% provide(:title, "Edit Task") %>

<div class="container border border-dark shadow w-50 rounded-2 p-2 mt-4 ">


<div class="text-start w-50 mx-auto" >
<%= form_with(model: @task, local: true) do |f| %>

<%= f.label :tname, "Title" %>
<br>
<%= f.text_field :tname %>
<br>
<br>

<%= hidden_field_tag(:pid, @project.id) %>
<%= f.submit "Update Task", class: "btn btn-outline-success" %>

<% end %>
</div>
</div>

app/views/tasks/index.html.erb
<% provide(:title, "All Tasks") %>

<div class="container mt-4">
<% if !@tasks.empty? %>
<h1 class="mb-4">List Of All Tasks</h1>
<table class="table">
  <tbody>
      <tr>
      <th scope="col">No</th>
      <th scope="col">Tasks</th>

    </tr>
  </thead>
  <% @count = 0 %>
    <% @tasks.each do |task| %>
    <tr>
      <th scope="row"><%= @count += 1 %></th>
      <td><%= task.tname %></td>
      <td><%= link_to "Update", edit_task_path(task, pid: @project.id) %></td>
      <td><%= link_to "Delete", task_path(task, pid: @project.id), method: :delete %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<% else %>
<h2>No tasks</h2>
<% end %>
<%= link_to "Create New Task", new_task_path(pid: @project.id) %>
</div>

app/views/tasks/new.html.erb
<div class="container border border-dark shadow w-50 rounded-2 p-2 mt-4 ">


<div class="text-start w-50 mx-auto" >
<%= form_with(model: @task, local: true) do |f| %>

<%= f.label :pname, "Title" %>
<br>
<%= f.text_field :tname %>
<br>
<br>


<%= hidden_field_tag(:pid, @pid) %>
<%= f.submit "Create Task", class: "btn btn-outline-success" %>

<% end %>
</div>
</div>

app/views/users/new.html.erb
<% provide(:title, "SignUp") %>

<div class="container border border-dark shadow w-50 rounded-2 p-2 mt-4 ">

<h1 class="text-center">Sign Up</h1>
<div class="text-start w-50 mx-auto" >
<%= form_with(model: @user, local: true) do |f| %>

<%= f.label :email, "Email" %>
<br>
<%= f.email_field :email %>
<br>
<br>

<%= f.label :password, "Password" %>
<br>
<%= f.password_field :password %>
<br>
<br>

<%= f.label :password_confirmation, "Confirm Password" %>
<br>
<%= f.password_field :password_confirmation %>
<br>
<br>

<%= f.submit "Create Account", class: "btn btn-outline-success" %>
<br>
<%= link_to "have account?", login_path %>


<% end %>
</div>
</div>